services:
  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rails_network

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec bin/rails server -b '0.0.0.0'"
    volumes:
      - ".:/app"
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - rails_network

volumes:
  postgres_data:

networks:
  rails_network:
    driver: bridge
