version: '3'

networks:
  rails-network:
    driver: bridge

services:
  web:
    build: .
    restart: no
    env_file: .env
    ports:
      - "3001:3000"
    volumes:
      - .:/app:cached
    depends_on:
      - db
    networks:
      - rails-network
    command: >
      sh -c "
      bundle install &&
      bundle exec rails db:migrate &&
      if [ $RAILS_ENV = 'production' ]; then
        bundle exec rails assets:precompile;
      fi &&
      rm -f tmp/pids/server.pid &&
      bundle exec rails s -b 0.0.0.0
      "

  db:
    image: postgres:16
    restart: no
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rails-network

volumes:
  pgdata: